# Generated by Django 4.1.3 on 2022-12-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
