# Generated by Django 4.1.3 on 2022-12-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main/profile/profile_default.png', upload_to='main/profile/'),
        ),
    ]
